<<<<<<< HEAD
version: '3'
services:
  react-app:
    image: react-app-image
    build:
      context: .
    volumes:
      - react-app-build:/app/dist

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - react-app-build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  react-app-build:
=======
version: '3.1'

services:
  letsencrypt-nginx-container:
    container_name: 'letsencrypt-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt-site:/usr/share/nginx/html
    networks:
      - docker-network


networks:
  docker-network:
    driver: bridge

>>>>>>> 3rd_build
